# This workflow will build and test both the front-end and back-end unconditionally
# when changes are detected in either of the folders.

name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "front-end/**"
      - "back-end/**"
  pull_request:
    branches: ["main"]
    paths:
      - "front-end/**"
      - "back-end/**"

jobs:
  front-end-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies, build, and test - Front-end
        working-directory: ./front-end
        run: |
          npm ci
          npm run build --if-present
          npm test

  # back-end-build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [18.x, 20.x, 22.x]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - name: Install dependencies, build, and test - Back-end
  #       working-directory: ./back-end
  #       run: |
  #         npm ci
  #         npm run build --if-present
  #         npm test
